version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
- package-ecosystem: bundler
  directory: "/docs"
  schedule:
    timezone: Europe/Berlin
    interval: daily
    time: "02:50"
  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    timezone: Europe/Berlin
    interval: daily
    time: "02:50"
  open-pull-requests-limit: 10

- package-ecosystem: npm
  directory: "/"
  target-branch: main-0.10.x
  schedule:
    interval: daily
    time: "03:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
- package-ecosystem: composer
  directory: "/"
  target-branch: main-0.10.x
  schedule:
    interval: daily
    time: "03:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  directory: "/"
  target-branch: main-0.10.x
  schedule:
    timezone: Europe/Berlin
    interval: daily
    time: "02:50"
  open-pull-requests-limit: 10


